import './globals.css'
import { M_PLUS_1 } from 'next/font/google'

import NabBar from '@/components/nav-bar/nav-bar'

import type { Metadata } from 'next'

const mPlus1 = M_PLUS_1({ subsets: ['latin'], weight: ['200', '400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className={mPlus1.className}>
        <NabBar />
        {children}
      </body>
    </html>
  )
}
