import './globals.css'

import NabBar from '@/components/nav-bar/nav-bar'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className='bg-app-bg text-app-text'>
        <NabBar />
        {children}
      </body>
    </html>
  )
}
