export { makeGetDocumentResponse } from './get-document'
export { makeGetDocumentsResponse } from './get-documents'
export { makeGetTagResponse } from './get-tag'
export { makeGetTagsResponse } from './get-tags'
export { makeGetWebsitesResponse } from './get-websites'
